language: c
compiler:
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bc tcsh
  - make
  - source ./util/setchplenv.bash
script:
  - ./util/start_test -futures test/release/examples
env:
  - CHPL_DEVELOPER=true
