language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang


script:
  - ./util/buildRelease/smokeTest

env:
  - NIGHTLY_TEST_SETTINGS=true

sudo: false
