language: c
compiler:
  - clang
  - gcc
before_script:
  - make
  - source ./util/setchplenv.bash
script:
  - '[ "$(./util/devel/lookForTabs | wc -l)" = "0" ] || (echo "Found tabs :-(" ; false)'
  - ./util/start_test -futures test/release/examples
env:
  - CHPL_DEVELOPER=true
